config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/' => 'pages#home', as: 'home'
  get '/brrr' => 'twitch#brrr'
  get '/mcmods' => 'pages#mcmods'
  get '/resume' => 'pages#resume'
  get '/happynothappy' => 'pages#hnh'
  post '/happynothappy' => 'pages#hnh_r'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mod.rb
# frozen_string_literal: true

class Mod < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

require 'net/http'

class PagesController < ApplicationController
  # GET /mcmods
  def mcmods
    @mods = Mod.all
  end

  # GET /resume
  def cv; end

  # GET /happynothappy
  def hnh; end

  # POST /happynothappy
  def hnh_r
    # reCAPTCHA
    resp = params['g-recaptcha-response']
    secret = ENV.fetch('CAPTCHA_SECRET', nil)
    uri = URI.parse('https://www.google.com/recaptcha/api/siteverify')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.path, { 'Content-Type' => 'application/x-www-form-urlencoded' })
    request.body = "secret=#{secret}&response=#{resp}"
    response = http.request(request)
    render status: :bad_request if JSON.parse(response.body)['success'] != true

    addr = params[:contact]
    msg = params[:content]
    msg_p = 'msg'
    fn = Time.zone.now.strftime('%Y-%m-%d_%H:%M:%S.%L.txt')
    begin
      Dir.mkdir(msg_p) unless File.exist?(msg_p)
      File.write("#{msg_p}/#{fn}", "From: #{addr}\n#{msg}")
    rescue StandardError => e
      raise e unless Rails.env.production?

      Rails.logger.debug e
      render status: :internal_server_error
    end
  end
end

app/controllers/twitch_controller.rb
# frozen_string_literal: true

require 'net/http'

class TwitchController < ApplicationController
  include TwitchHelper

  # GET /brrr
  def brrr
    query
    @is_printing = printing?
    @is_alive = alive?
    @job_name = job_name
  end

  private
  #################
  # Custom errors #
  #################
  class EnvironmentException < StandardError
  end

  ########
  # Init #
  ########
  def query
    @connection = get '/api/connection'
    @job = get '/api/job'
  end

  ###################
  # Boolean getters #
  ###################
  def printing?
    @connection == nil ? false : @connection['current']['state'] == 'Printing'
  end

  def alive?
    @connection == nil ? false : @connection['current']['state'] != 'Closed'
  end

  def job_name
    def name(n)
      n == nil ? "<no_job>" : n.split('.')[0..-2].join('.')
    end

    @job == nil ? "<no_job>" : name(@job['job']['file']['name'])
  end

  ################
  # HTTP related #
  ################
  def get(route)
    begin
      resp = send_request route
      JSON.parse resp.gsub('=>', ':')
    rescue => e
      warn e
      nil
    end
  end

  def send_request(route, _content = '', type = 'GET', headers = {})
    tries = 5
    key = ENV.fetch('OCTOPRINT_APIKEY', nil)
    url = ENV.fetch('OCTOPRINT_URL', nil)
    if key == nil or url == nil
      raise EnvironmentException.new "Octoprint envvar not loaded"
    end

    host = url.include?('://') ? url.split('://')[1] : url
    headers = { 'Host' => host,
                'X-Api-Key' => key }.merge(headers)

    # TODO refactor
    headers_arr = []
    headers.each { |k,v| headers_arr.append "-H #{[k,v].join ':'}" }
    res = `curl -s -L #{url}#{route} #{headers_arr.join ' '}`
    res
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active?(action)
    current_page?({ controller: 'pages', action: action }) ? ' active' : ''
  rescue StandardError
    current_page?({ controller: 'twitch', action: action }) ? ' active' : ''
  end
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
  # Mods page
  def write_mod_page(mod)
    %(
    <div class="mod">
      <a href="#{mod.webpage}" target="_blank">
        <div class="row">
          <div class="col-md-2 flex-center">
            <img src="#{mod.logo}" alt="#{mod.name}_logo" class="responsive-img" />
          </div>
          <div class="col-md-10 mod-desc">
            <h2>#{mod.name}</h2>
            <span>#{mod.desc}</span>
          </div>
        </div>
      </a>
    </div>
    ).html_safe
  end

  # Resume related
  def write_job_desc(title, company, website, location, dates, desc)
    %(
    <div class="row">
      <div class="job-title">
        <p>#{title}</p>
        <p>#{link_to company, website, target: '_blank', rel: 'noopener'}, #{location}</p>
        <p>#{dates}</p>
      </div>
      <p class="job-desc">&emsp;#{desc}</p>
    </div>
    ).html_safe
  end
end

app/helpers/twitch_helper.rb
# frozen_string_literal: true

module TwitchHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%=
      if content_for?(:title) then
        "#{yield :title} | Chocorp"
      else
        'Chocorp'
      end
      %></title>
    <meta charset="utf-8">
    <meta name="keywords" content="chocorp, baptiste, chocot">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="chocorp.net - Baptiste Chocot">
    <meta name="author" content="Baptiste Chocot">
    <meta name="robots" content="index, follow">

    <%= render 'application/favicon' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= if content_for(:title) then
      case "#{yield :title}"
      when 'Mods'
        stylesheet_link_tag 'mcmods'
      when 'Resume'
        stylesheet_link_tag 'cv'
      when 'Feedback'
        stylesheet_link_tag 'hnh'
      end
    end
    %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-expand-md navbar-dark bd-navbar">
      <%= link_to image_tag('icon.svg', class: 'd-block', alt: 'chocorp.net'), root_path %>
      <button id="hamburger" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#headerNavbar" aria-controls="headerNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="headerNavbar">
        <div class="navbar-nav-scroll">
          <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav pt-2 py-md-0">
            <li class="nav-item col-6 col-md-auto">
              <%= link_to 'Home', root_path, class: 'nav-link' + active?('home') %>
            </li>
            <li class="nav-item col-6 col-md-auto">
              <%= link_to '3d-printing stream', brrr_path, class: 'nav-link' + active?('brrr') %>
            </li>
          </ul>
        </div>
        <div class="navbar-nav-scroll">
          <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav pt-2 py-md-0">
            <li class="nav-item col-6 col-md-auto">
              <%= link_to 'Mods', mcmods_path, class: 'nav-link' + active?('mcmods') %>
            </li>
            <li class="nav-item col-6 col-md-auto">
              <%= link_to 'Resume', resume_path, class: 'nav-link' + active?('resume') %>
            </li>
          </ul>
        </div>
        <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav pt-2 py-md-0 ms-md-auto">
          <li class="nav-item col-6 col-md-auto">
            <%= link_to 'Contact', happynothappy_path, class: 'nav-link' + active?('hnh') %>
          </li>
          <li class="nav-item col-6 col-md-auto">
            <%= link_to 'Chocoprint', 'https://print.chocorp.net', class: 'nav-link external' %>
          </li>
        </ul>
      </div>
    </header>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <footer>
    </footer>
  </body>
</html>

app/views/pages/hnh.html.erb
<%= provide(:title, 'Feedback') %>
<div id="body-middle">
  WIP
  <!-- 
  <h1>Wanna say something? That's the place to be.</h1><hr /><br />
  <%= form_with url: "/happynothappy", id: "feedback_form", method: :post, local: false do |form| %>
    <div class="row form-group">
      <div class="offset-sm-2 col-sm-2">
        <%= form.label :contact, "Email address:" %>
      </div>
      <div class="col-sm-6">
        <%= form.email_field :contact, class: "form-control", required: true %>
      </div>
    </div>
    <br />
    <div class="row form-group">
      <div class="offset-sm-2 col-sm-8">
        <%= form.label :content, "Write your comments below:" %>
      </div>
    </div>
    <div class="row form-group">
      <div class="offset-sm-2 col-sm-8">
        <%= form.text_area :content, class: "form-control", required: true %>
      </div>
    </div><br />
    <div class="form-group">
      <button id="hnh_button" class="g-recaptcha btn btn-success offset-sm-2" data-sitekey="<%= ENV['CAPTCHA_SITEKEY'] %>" data-callback='onSubmit' data-action='submit'>Send</button>
    </div>
  <% end %>
  <div class="row">
    <div id="xhr_success" class="offset-sm-2">Thanks for your feedback.</div>
  </div>
  <div class="row">
    <div id="xhr_fail" class="offset-sm-2">An issue happened. Please try again later.</div>
  </div>
  -->
</div>
<script src="https://www.google.com/recaptcha/api.js"></script>

app/views/pages/home.html.erb
<%= provide(:title, "Home") %>
<div id="body-middle">
  <h1>chocorp.net</h1>
  <div class="row">
    <%= link_to 'Check https://chocorp.net', 'https://check-your-website.server-daten.de/?q=chocorp.net', target: '_blank' %>
  </div>
  <div class="row">
  <%= link_to 'chocorp.net Trello board', 'https://trello.com/c/0LKMxe5K', target: '_blank' %>
  </div>
  <div class="row">
    <p>WIP. Please don't mind the remaining French sentences. This webpage is supposed to host my future projects.</p>
    <p>Not reliable list of incoming projects/pages:</p>
    <ul class="col-md-8 list-group">
      <li class="list-group-item">smth nice with open data would be great</li>
      <li class="list-group-item">crypto stonks - symbols tracker/idk yet its just hype</li>
      <li class="list-group-item">I'd love to build smth the community could interact with qnd interqctions would impqct other users...</li>
      <li class="list-group-item">inteam bros</li>
    </ul>
  </div>
</div>

app/views/pages/mcmods.html.erb
<%= provide(:title, "Mods") %>
<div id="body-middle">
  <div id="mods">
    <h1>Minecraft Mods</h1>
    <%=
      buffer = []
      for mod in @mods do
        buffer.append(write_mod_page(mod))
      end
      buffer.join("\n").html_safe
    %>
  </div>
</div>

app/views/pages/resume.html.erb
<%= provide(:title, "Resume") %>
<div id="cv">
    <h1>Baptiste CHOCOT - <strong>Software & Cyber-Sec Engineer</strong></h1></h1>
    <h3>Looking for a challenging position abroad</strong></h3>
    <hr />
    <div class="row">
        <div id="left" class="col-md-3">
            <div class="row justify-content-center">
                <%= image_tag('/cv/img/tete.png', id: 'photo', alt: 'Baptiste CHOCOT') %>
            </div>
            <div class="row left">
                <h4>Personal information</h4>
                <div>+1 202-897-7791</div>
                <p><%= link_to 'baptiste.chocot@pm.me', 'mailto:baptiste.chocot@pm.me?subject=Hello there!' %>
                <p>
                  <%= link_to image_tag('/cv/img/GitHub-Mark-32px.png'), 'https://github.com/Chocorean', target: '_blank', class: 'logo', alt: 'GitHub' %>
                  <%= link_to image_tag('https://www.root-me.org/squelettes/img/rblackGrand32.png', alt: 'RootMe', class: 'logo'), 'https://www.root-me.org/?chocot', target: '_blank' %>
                  <a href="https://linkedin.com/in/baptiste-chocot-82188a149" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" data-supported-dps="24x24" fill="currentColor" class="mercado-match" width="24" height="24" focusable="false">
                      <path d="M20.5 2h-17A1.5 1.5 0 002 3.5v17A1.5 1.5 0 003.5 22h17a1.5 1.5 0 001.5-1.5v-17A1.5 1.5 0 0020.5 2zM8 19H5v-9h3zM6.5 8.25A1.75 1.75 0 118.3 6.5a1.78 1.78 0 01-1.8 1.75zM19 19h-3v-4.74c0-1.42-.6-1.93-1.38-1.93A1.74 1.74 0 0013 14.19a.66.66 0 000 .14V19h-3v-9h2.9v1.3a3.11 3.11 0 012.7-1.4c1.55 0 3.36.86 3.36 3.66z"></path>
                    </svg>
                  </a>
                </p>

                
            </div>
            <div class="row left">
              <div class="col-sm-6 col-md-12">
                <h4>Soft skills</h4>
                <p>Autonomous</p>
                <p>Flexible</p>
                <p>Meticulous</p>
                <p>Curiosity-driven</p>
              </div>
              <div class="col-sm-6 col-md-12">
                <h4>Misc</h4>
                <p><%= link_to 'Raspberry PIs', 'https://www.raspberrypi.org/' %></p>
                <p><%= link_to 'ClickHouse', 'https://clickhouse.tech/', target: '_blank' %> by Yandex</p>
                <p>Minecraft modding and <%= link_to 'Forge', 'http://files.minecraftforge.net/', target: '_blank' %></p>
            </div>
          </div>
        </div>
        <hr class="v-sep" />
        <div id="right" class="col-md-9">
            <div class="row">
                <h4>About me</h4>
                <p class="job-desc">&emsp;I am a French IT engineer currently looking for something new and exciting to do. My main skills are software development and a good base for cyber security. I currently live in the USA, but I am willing to discover new countries and cultures.</p>
            </div>
            <div class="row">
                <h4>Former positions</h4>
                <%= write_job_desc 'Computer Scientist', 'NIST', 'https://www.nist.gov', 'Gaithersburg, MD', 'Jan, 5 2020 - Today', "I am a member of the team dedicated to the #{link_to 'OpenMFC challenge', 'https://mfc.nist.gov'} sponsored by IARPA. I am working on deepfakes detection, am responsible for generating deepfake datasets on a GPGPU infrastructure, and managing a student from a local university." %>
                <%= write_job_desc 'Software Engineer', 'NIST', 'https://www.nist.gov', 'Gaithersburg, MD', 'Jan, 5 2020 - Jan, 4 2022', "I was a member of the team dedicated to the #{link_to 'ActEV challenge', 'https://actev.nist.gov'} sponsored by IARPA. I am responsible for maintenance and development of new features for two projects, an abstract CLI that our partners have to implement, then submit to our pipeline, and a scorer software which evaluates our partners software's performance. Aditionnaly, I had to reimagine the CI for the abstract CLI because it became harder to test. I am also responsible for the generation of some ActEV datasets." %>
                <%= write_job_desc 'Cyber-security trainee', 'Excellium Services', 'https://excellium-services.com/', 'Contern, Luxembourg', 'March, 01 - September, 30 2019', 'The goal of the internship was to create from scratch a data leak orchestration tool, which would store any leaked credential of the company\'s customers, for monitoring purposes. I designed the software as a web API for ease of use by the other tools of the company. I have used an analytical database called <strong>ClickHouse</strong>, which is currently holding billions of leaked credentials and has crazy fast response times. It is currently part of the firm\'s monitoring offer.' %>
            </div>
            <div class="row">
                <h4>Technical skills</h4>
                <div class="col-sm-6 col-md-4">
                  <h5>Very confortable with:</h5>
                  <ul class="skills">
                    <li>Python, Shell</li>
                    <li>UNIX-like systems</li>
                    <li>Various cyber-security concepts</li>
                  </ul>
                </div>
                <div class="col-sm-6 col-md-4">
                  <h5>Confortable with:</h5>
                  <ul class="skills">
                    <li>Rust 🦀</li>
                    <li>C/C++, Java, PHP, Ruby/ROR</li>
                    <li>Docker</li>
                    <li>ClickHouse, MySQL databases</li>
                  </ul>
                </div>
                <div class="col-sm-6 col-md-4">
                  <h5>Already used:</h5>
                  <ul class="skills">
                    <li>Monitoring (Nagios, Grafana)</li>
                    <li>VBox, VMWare</li>
                    <li>Firewalls (iptables)</li>
                  </ul>
                </div>
            </div>
            <div class="row">
                <h4>Education</h4>
                <%= write_job_desc 'IT Engineer/Master Degree - Cyber-security major', 'Télécom Nancy', 'https://telecomnancy.univ-lorraine.fr/', 'Nancy, France', '2016-2019', "Including 11 months of internship, several group projects, such as an Hex game (and its AI), a mini-rust compiler, mini-#{link_to 'nmap', 'https://nmap.org'}, or an #{link_to 'UrbanLoop', 'http://urbanloop.univ-lorraine.fr/'} network simulator." %>
                <%= write_job_desc 'French prep school', 'Lycée Benjamin Franklin', 'http://www.lycee-benjamin-franklin.fr/php5/spip/', 'Orléans, France', '2014-2016', '2-year class preparing a competitive entrance examination to engineering schools.' %>
                <%= write_job_desc 'Baccalauréat S', 'Lycée François Villon', 'https://www.legtfrancoisvillon.fr/', 'Beaugency, France', '2014', 'Scientific bac, major "engineer sciences", Python introduction, with <i>good</i> honors.' %>
            </div>
        </div>
    </div>
</div>

app/views/twitch/brrr.html.erb
<%= provide(:title, "3D-printing") %>
<div id="body-middle">
  <h1>Hi Twitch!</h1>
  <div>
    <p>I recently (Dec. 2020)  bought my first 3D-printer, an Ender 3 from Creality. It will start a stream on Twitch anytime I print something, and post a timelapse on Youtube. I'll also list here the models I'll be making.</p>
  </div>
  <br />
  <div>
  <% if @is_printing %>
    The printer is currently printing <strong><%= "#{@job_name} " %></strong>! Check it out <%= link_to 'here', 'https://print.chocorp.net/#control' %> (credentials: guest/guest).
  <% elsif ! @is_alive %>
    The printer is likely off.
  <% else %>
    The printer is not busy at the moment.
  <% end %>
  </div>
  <hr />
  <h4>Youtube corner - WIP</h4>
  <div class="row">
    <div class="col-6">
      <iframe width="560" height="315" src="https://www.youtube.com/embed/txHBOYy_VAY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
  </div>
</div>